### ISSUE TITLE
Can't Erase and Program on a Mac

### ISSUE THREAD

**Issue by estiens** [DeepSea-Developments/DeepDeck.programmer#4]
Getting this error right after it flashes the ESP but it's impossible to tell if it is still doing something (it hasn't existed...) so I'll leave it for awhile...

```
Hard resetting via RTS pin...
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter/__init__.py", line 1948, in __call__
  File "app.py", line 144, in on_program_erase_button_click
  File "app.py", line 179, in program_and_erase
UnboundLocalError: cannot access local variable 'e' where it is not associated with a value
```

**Comment by estiens** [comment]
hmmm, I'm guessing it is just trying to display an error there and unable to talk about it for some reason...figured out it was because it couldn't find a binary for 0.5.7 but when I programmed 0.5.6 it worked fine :d
